Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.boot_timeout = 1200
  config.ssh.insert_key = true
  # config.ssh.private_key_path = "/collections/ansible-collections/kubernetes/sazebtech/.vagrant/vagrant_key"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2 
  end
end
