---
- name: Create EC2 instance
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Launch EC2 instance
    amazon.aws.ec2_instance:
      name: molecule-instance
      instance_type: t2.medium
      image_id: "{{ hostvars['molecule_instance']['image_id'] }}"
      region: "{{ hostvars['molecule_instance']['region'] }}"
      key_name: "{{ hostvars['molecule_instance']['key_name'] }}"
      security_group: "{{ hostvars['molecule_instance']['security_group'] }}"
      network:
        assign_public_ip: true
        subnet_id: "{{ hostvars['molecule_instance']['subnet_id'] }}"
      wait: yes
      state: present
    register: ec2_instance

  - name: Add instance to Molecule inventory
    delegate_to: localhost
    ansible.builtin.add_host:
      name: "{{ ec2_instance.instances[0].instance_id }}"
      ansible_host: "{{ ec2_instance.instances[0].public_ip_address }}" # Changed this line
      ansible_user: ec2-user
      ansible_private_key_file: ~/ansible-keypair.pem