---
# - name: Update Machine Packages
#   package:
#     name: "{{ item }}"
#     state: present
#   loop: "{{ packages_to_install }}"

# - name: Disable Swap
#   command: swapoff -a

# - name: Comment out /etc/fstab
#   lineinfile:
#     path: /etc/fstab
#     regexp: '^.*\s+swap\s+'
#     line: '#\0'
#     backrefs: true

# - name: Load br_netfilter kernel module
#   command: modprobe br_netfilter

# - name: Add netfilter to /etc/modules-load.d/k8s.conf
#   copy:
#     content: 'br_netfilter'
#     dest: /etc/modules-load.d/k8s.conf
#     owner: root
#     group: root
#     mode: '0644'

# - name: Enable netfilter for iptables
#   sysctl:
#     name: net.bridge.bridge-nf-call-iptables
#     value: '1'
#     state: present
#     reload: true

# - name: Enable netfilter for ip6tables
#   sysctl:
#     name: net.bridge.bridge-nf-call-ip6tables
#     value: '1'
#     state: present
#     reload: true

- name: Add Docker's official GPG key
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  become: yes

- name: Add Docker stable repository
  ansible.builtin.shell: |
    echo "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable" | tee /etc/apt/sources.list.d/docker.list
  args:
    executable: /bin/bash
  register: docker_repo_added

- name: Clean APT cache
  ansible.builtin.apt:
    autoclean: yes

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Update the package list
  ansible.builtin.apt:
    update_cache: yes
  when: docker_repo_added.changed

- name: Install Docker packages
  ansible.builtin.apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present
    update_cache: yes

- name: Verify Docker installation
  ansible.builtin.command: docker --version
  register: docker_version_output
  changed_when: false
  ignore_errors: yes

- name: Display Docker version
  ansible.builtin.debug:
    msg: "Docker version installed: {{ docker_version_output.stdout }}"